export const destinationEnglish:Record<string,{name:string;description:string;alt:string;highlights:string[]}>= {
  india:{name:'India',description:'A diverse education destination with many universities and colleges and extensive options in technology, engineering, business, and health sciences.',alt:'Study in India',highlights:['A wide range of universities and majors','Programs taught in English','Options for different budgets','Well-known student cities such as Bangalore']},
  malaysia:{name:'Malaysia',description:'A modern, multicultural study environment with international universities and academic programs for students from around the world.',alt:'Study in Malaysia',highlights:['International university environments','Programs taught in English','Comfortable student life','Diverse business and technology options']},
  china:{name:'China',description:'An advanced destination for engineering, technology, and science, with major universities and diverse academic opportunities.',alt:'Study in China',highlights:['Strength in engineering and technology','Advanced universities and laboratories','A variety of international programs','A distinctive cultural and educational experience']},
  russia:{name:'Russia',description:'Known for medicine, engineering, and science programs, with varied options for international students across several university cities.',alt:'Study in Russia',highlights:['Recognized medicine and engineering programs','Universities welcoming international students','Multiple academic options','Support throughout application and admission']},
  turkey:{name:'Türkiye',description:'Modern education in a familiar cultural setting, with public and private universities and a broad range of programs.',alt:'Study in Türkiye',highlights:['Public and private universities','Programs in Turkish and English','A welcoming environment for international students','An attractive location and culture']},
}

export const destinationWhatsapp=(language:'ar'|'en',country:string)=>language==='ar'?`مرحبًا أستاذ علي، أرغب في معرفة تفاصيل الدراسة والتسجيل في ${country}.`:`Hello Mr. Ali, I would like more information about studying and applying in ${country}.`
