export const en = {
  languages: { arabic: 'Arabic', english: 'English' },
  destinations: {
    available: 'Study destination available for application', globalTitle: 'Our Study Destinations Around the World',
    india: { name:'India', flightLabel:'To India', viewLabel:'View study information for India' },
    malaysia: { name:'Malaysia', flightLabel:'To Malaysia', viewLabel:'View study information for Malaysia' },
    china: { name:'China', flightLabel:'To China', viewLabel:'View study information for China' },
    russia: { name:'Russia', flightLabel:'To Russia', viewLabel:'View study information for Russia' },
    turkey: { name:'Turkey', flightLabel:'To Turkey', viewLabel:'View study information for Turkey' },
    bangalore: { name:'Bangalore', flightLabel:'To Bangalore', viewLabel:'View study information for Bangalore' },
  },
  hero: { eyebrow: 'Your future begins with a confident step', title: 'Start Your University Journey', accent: 'with Confidence at ElSheik Agency', description: 'We help you choose the right university and program, complete your admission and registration process, and support your educational journey every step of the way.', primary: 'Start Your Application', secondary: 'Explore Colleges', trust: ['Personal Guidance','Clear Information','Fast Support'], stepTitle: 'Step by Step', stepDescription: 'From selection to admission' },
  about: { eyebrow: 'My Journey in Education', title: 'About Me', lead: 'I’m Ali ElSheik, your guide throughout your university journey.', paragraph1: 'I studied in Bangalore, India, where I gained first-hand experience with universities, colleges, admission procedures, and student life. I founded ElSheik Education Agency to help students make informed and confident academic decisions.', paragraph2: 'I understand that choosing a university and major, preparing to study abroad, and completing admission requirements can feel overwhelming. That is why I provide personal guidance and continuous support from the first consultation until registration is complete.', highlights: ['First-hand study experience in India','Personal student support','Help choosing a major','Support throughout registration'], badge: 'Experience from the Heart of Bangalore', imageAlt: 'Ali ElSheik, founder of ElSheik Education Agency' },
  services: { eyebrow: 'How Can We Help?', title: 'Services Designed for Your Education Journey', description: 'Everything you need to make a clear decision and start with confidence, all in one place.', items: [
    ['Education Consulting','We help students understand the available options and choose the educational path that best fits their goals.'],
    ['University and Major Selection','We compare suitable universities and programs based on the student’s interests, budget, academic background, and future plans.'],
    ['University Applications and Admission','We help prepare applications and documents and follow up on admission procedures.'],
    ['College Registration','We provide complete support for registration at the selected university or college.'],
    ['Student Support','We support students from the beginning of the process until admission and registration are completed.'],
    ['Study in Bangalore','We provide guidance for students who want to study in Bangalore, India.'] ] },
  why: { eyebrow: 'Why Choose Us?', title: 'Because Your Academic Decision Deserves Care', description: 'We do more than provide a list of options. We listen to you and help you build an academic path that matches your goals and circumstances.', button: 'Chat with Ali Now', items: ['First-hand knowledge of student life and study in Bangalore','Personal guidance for every student','Clear and reliable information','Continuous follow-up on registration requests','Support for students and families when making decisions','Fast support through WhatsApp'] },
  colleges: { eyebrow: 'Your Opportunity Starts Here', title: 'Colleges and Universities', description: 'Explore some available academic paths. We will help you verify the latest details and choose the best option.', loadError: 'We could not load the colleges.', retry: 'Try Again', empty: 'No colleges are currently available.' },
  steps: { eyebrow: 'A Clear Path', title: 'Six Steps to Get Started', items: [
    ['Submit Your Details','Tell us about your goals, needs, and preferred field of study.'],['Choose a College and Major','We help you explore the most suitable available options.'],['Review Your Options','Attend a clear consultation session with an advisor.'],['Prepare Your Documents','Complete and verify the required documents.'],['Submit Your Application','We support you throughout the application process.'],['Track Your Application','We follow up with you until the process is complete.'] ] },
  application: { badge: 'Your First Step', title: 'Start Your Application', description: 'Submit your details, and we will contact you to help you choose the right college and major.', consultationTitle: 'Personal Consultation', consultationText: 'We take the time to understand your needs before recommending options.', contactTitle: 'Fast Communication', contactText: 'Contact us on WhatsApp at +91 9036102240.' },
  form: { labels: ['Full Name','Desired College','Major or Course','Phone Number','Email Address','Country','City','Education Level','Additional Notes'], placeholders: ['Enter your full name','Example: College of Engineering and Technology','Enter your preferred major','+91...','name@example.com','Country of residence','Your city','Example: High school or bachelor’s degree','Tell us how we can help'], optional: 'Optional', submit: 'Submit Request', submitting: 'Submitting Request…', success: 'Your request has been submitted successfully. We will contact you soon.', failure: 'We could not submit your request. Please try again.', validation: { name:'Full name is required.', college:'College is required.', course:'Major or course is required.', phone:'Enter a valid phone number.', email:'Enter a valid email address.' } },
  whatsapp: { button: 'Chat with Us', message: 'Hello Mr. Ali, I would like more information about university admission services.' }
} as const
