import { useEffect, useState } from 'react'
import { ImagePlus, Pencil, Plus, Trash2, X } from 'lucide-react'
import { requireSupabase } from '../lib/supabase'
import type { College } from '../types'
import ConfirmModal from '../components/admin/ConfirmModal'
import Toast from '../components/admin/Toast'

type Draft = Omit<College,'id'|'college_courses'> & { id?:string; courses:string }
const empty:Draft={name:'',short_description:'',description:'',location:'',website_url:'',image_url:'',is_active:true,display_order:0,courses:''}

export default function AdminCollegesPage(){
 const [items,setItems]=useState<College[]>([]),[loading,setLoading]=useState(true),[form,setForm]=useState<Draft|null>(null),[busy,setBusy]=useState(false),[preview,setPreview]=useState(''),[remove,setRemove]=useState<College|null>(null),[toast,setToast]=useState<{message:string;type:'success'|'error'}|null>(null)
 const load=async()=>{setLoading(true);const{data,error}=await requireSupabase().from('colleges').select('*,college_courses(*)').order('display_order');if(error)setToast({message:'تعذر تحميل الكليات.',type:'error'});else setItems(data as College[]);setLoading(false)}
 useEffect(()=>{void load()},[])
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(null),3000);return()=>clearTimeout(t)},[toast])
 const edit=(c:College)=>{setPreview(c.image_url||'');setForm({...c,courses:c.college_courses.map(x=>x.name).join('، ')})}
 const choose=(file?:File)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024){setToast({message:'اختر صورة JPG أو PNG أو WEBP بحجم أقل من 5 ميجابايت.',type:'error'});return}setPreview(URL.createObjectURL(file));setForm(x=>x?({...x,_file:file} as Draft):x)}
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!form)return;setBusy(true);const client=requireSupabase();try{let image=form.image_url;const file=(form as Draft&{_file?:File})._file;if(file){const path=`${crypto.randomUUID()}-${file.name.replace(/[^\w.-]/g,'')}`;const{error}=await client.storage.from('college-images').upload(path,file);if(error)throw error;image=client.storage.from('college-images').getPublicUrl(path).data.publicUrl}const payload={name:form.name,short_description:form.short_description,description:form.description,location:form.location,website_url:form.website_url,image_url:image,is_active:form.is_active,display_order:Number(form.display_order)};let id=form.id;if(id){const{error}=await client.from('colleges').update(payload).eq('id',id);if(error)throw error;await client.from('college_courses').delete().eq('college_id',id)}else{const{data,error}=await client.from('colleges').insert(payload).select('id').single();if(error)throw error;id=data.id}const courses=form.courses.split(/[،,]/).map(x=>x.trim()).filter(Boolean);if(courses.length){const{error}=await client.from('college_courses').insert(courses.map(name=>({college_id:id,name})));if(error)throw error}setForm(null);setToast({message:'تم حفظ الكلية والتخصصات.',type:'success'});await load()}catch{setToast({message:'تعذر حفظ الكلية أو رفع الصورة.',type:'error'})}finally{setBusy(false)}}
 const destroy=async()=>{if(!remove)return;const{error}=await requireSupabase().from('colleges').delete().eq('id',remove.id);if(error)setToast({message:'تعذر حذف الكلية.',type:'error'});else{setToast({message:'تم حذف الكلية.',type:'success'});setItems(x=>x.filter(c=>c.id!==remove.id))}setRemove(null)}
 return <section className="dash-content">{toast&&<Toast {...toast}/>}<div className="dash-title"><div><span>المحتوى التعليمي</span><h1>إدارة الكليات</h1></div><button className="btn primary" onClick={()=>{setPreview('');setForm(empty)}}><Plus/> إضافة كلية</button></div>{loading?<div className="page-loader compact">جارٍ تحميل الكليات...</div>:!items.length?<div className="admin-empty">لا توجد كليات مضافة حاليًا.</div>:<div className="admin-college-grid">{items.map(c=><article key={c.id}><div className="admin-college-image">{c.image_url?<img src={c.image_url} alt={c.name}/>:<ImagePlus/>}</div><div><span className={`status ${c.is_active?'completed':'rejected'}`}>{c.is_active?'مفعلة':'مخفية'}</span><h3>{c.name}</h3><p>{c.short_description}</p><small>{c.college_courses.length} تخصصات</small><div className="admin-row-actions"><button onClick={()=>edit(c)}><Pencil/> تعديل</button><button onClick={()=>setRemove(c)}><Trash2/> حذف</button></div></div></article>)}</div>}{form&&<div className="modal-backdrop"><form className="college-form" onSubmit={save}><button type="button" className="modal-close" onClick={()=>setForm(null)}><X/></button><h2>{form.id?'تعديل الكلية':'إضافة كلية جديدة'}</h2><div className="form-grid"><label>اسم الكلية<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>الموقع<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label className="full">وصف مختصر<input value={form.short_description} onChange={e=>setForm({...form,short_description:e.target.value})}/></label><label className="full">الوصف الكامل<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>رابط الموقع<input type="url" value={form.website_url} onChange={e=>setForm({...form,website_url:e.target.value})}/></label><label>ترتيب الظهور<input type="number" value={form.display_order} onChange={e=>setForm({...form,display_order:Number(e.target.value)})}/></label><label className="full">التخصصات <em>افصل بينها بفاصلة</em><input value={form.courses} onChange={e=>setForm({...form,courses:e.target.value})}/></label><label className="full image-picker">صورة الكلية<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>choose(e.target.files?.[0])}/>{preview&&<img src={preview} alt="معاينة صورة الكلية"/>}</label><label className="toggle"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> إظهار الكلية في الموقع العام</label></div><button className="btn primary" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الكلية'}</button></form></div>}{remove&&<ConfirmModal title="حذف الكلية" text="هل أنت متأكد من حذف هذه الكلية؟ لا يمكن التراجع عن هذا الإجراء." onClose={()=>setRemove(null)} onConfirm={()=>void destroy()}/>}</section>
}
